apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: blub
spec:
  components:
  - name: blub
    type: webservice
    properties:
      image: sselzer/blub
      port: 8080
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            name: blub
            key: OTEL_SERVICE_NAME
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: blub
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            name: blub
            key: PYROSCOPE_URL
    traits:
    - type: annotations
      properties:
        "prometheus.io/scrape": "true"
        "prometheus.io/path": /metrics
        "prometheus.io/port": "8080"
    - type: cpuscaler
      properties:
        min: 1
        max: 3
        cpuPercent: 80